export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const APPROVE_POSTS = 'APPROVE_POSTS';
export const REJECT_POSTS = 'REJECT_POSTS';

export const LOADING_POSTS = 'LOADING_POSTS';
